### ISSUE TITLE
Violating of Mirai's AGPLv3 license

### ISSUE THREAD

**Issue by Yuzurisa** [liaosunny123/EpicMoMiraiG#8]
This project relys on Mirai, which is AGPLv3. But this project seems not to be open source, which violates that license.
Please give us a response, thanks.

**Comment by liaosunny123** [comment]
I am sorry that I cannot check github issue regularly due to my study and I missed this issue.
This project is not really based on Mirai in the way that you think. As the README describes , this project helps Mirai start , deals with Mirai's files , carry out specific commands using cmd or modifying files , connecting with Mirai only with the help of HTTP API.
So this project does not use any code of Mirai and edits the code , which means that this project is not the target of the AGPLv3.

But this project is going to be open source.In fact , this project was to be open source but I delete them due to some reasons.I will make the project source-opened after I deal with the source and then update them.

**Comment by liaosunny123** [comment]
If you have any questions about this project , you can reopen this issue anytime or open a new issue about other questions.Thanks for your understanding and support to this project.
